
spring:
  datasource:
    url: "jdbc:mysql://172.17.0.3:3306/product_management"
    username: "root"
    password: "root"
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
debug: true
